function buildDirectory = generate_code()
%GENERATE_CODE Test and generate integration-ready BmsSupervisor C code.
%   Generated build workspace files are written under the repository's
%   top-level codegen/ directory.
%   This function intentionally does not copy files into src/generated; that
%   reviewed deployment/staging operation is a separate workflow step.

cfg = setup_model();
run_model_tests();

load_system(cfg.ModelFile);
cleanup = onCleanup(@()closeModel(cfg.ModelName));

activeConfig = getActiveConfigSet(cfg.ModelName);
set_param(cfg.ModelName, ...
    'SystemTargetFile', 'ert.tlc', ...
    'TargetLang', 'C', ...
    'GenCodeOnly', 'on', ...
    'GenerateSampleERTMain', 'off', ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', sprintf('%.17g', cfg.StepSeconds));

% The generic ERT installation does not expose a named Cortex-M3 production
% device without the optional ARM support package. Describe the STM32F103 ABI
% explicitly so code generation is still reproducible and target-correct.
set_param(activeConfig, ...
    'ProdHWDeviceType', 'Custom Processor->Custom', ...
    'ProdBitPerChar', 8, ...
    'ProdBitPerShort', 16, ...
    'ProdBitPerInt', 32, ...
    'ProdBitPerLong', 32, ...
    'ProdBitPerLongLong', 64, ...
    'ProdWordSize', 32, ...
    'ProdEndianess', 'LittleEndian', ...
    'ProdIntDivRoundTo', 'Zero', ...
    'ProdShiftRightIntArith', 'on');

validateConfiguration(cfg.ModelName);
slbuild(cfg.ModelName);

buildInfo = RTW.getBuildDir(cfg.ModelName);
buildDirectory = buildInfo.BuildDirectory;
validateGeneratedCode(cfg, buildDirectory);

fprintf('BmsSupervisor code generation passed.\n');
fprintf('  Build workspace: %s\n', buildDirectory);
fprintf('  Deployment staging was not performed.\n');
end

function validateConfiguration(modelName)
expected = { ...
    'SystemTargetFile', 'ert.tlc'; ...
    'TargetLang', 'C'; ...
    'GenCodeOnly', 'on'; ...
    'GenerateSampleERTMain', 'off'; ...
    'SolverType', 'Fixed-step'; ...
    'Solver', 'FixedStepDiscrete'; ...
    'FixedStep', '0.5'};
for row = 1:size(expected, 1)
    actual = get_param(modelName, expected{row, 1});
    if ~strcmp(actual, expected{row, 2})
        error('BmsSupervisor:InvalidCodeConfiguration', ...
            '%s must be %s, received %s.', ...
            expected{row, 1}, expected{row, 2}, actual);
    end
end

hardware = get_param(modelName, 'ProdHWDeviceType');
if ~strcmp(hardware, 'Custom Processor->Custom') || ...
        get_param(modelName, 'ProdBitPerInt') ~= 32 || ...
        get_param(modelName, 'ProdWordSize') ~= 32 || ...
        ~strcmp(get_param(modelName, 'ProdEndianess'), 'LittleEndian')
    error('BmsSupervisor:InvalidHardwareTarget', ...
        'Production hardware must describe the 32-bit little-endian STM32 ABI.');
end
end

function validateGeneratedCode(cfg, buildDirectory)
requiredFiles = {'BmsSupervisor.c', 'BmsSupervisor.h', ...
    'BmsSupervisor_types.h', 'rtwtypes.h'};
for fileIndex = 1:numel(requiredFiles)
    generatedFile = fullfile(buildDirectory, requiredFiles{fileIndex});
    if ~isfile(generatedFile)
        error('BmsSupervisor:MissingGeneratedFile', ...
            'Required generated file is missing: %s', generatedFile);
    end
end

if isfile(fullfile(buildDirectory, 'ert_main.c'))
    error('BmsSupervisor:UnexpectedGeneratedMain', ...
        'ert_main.c must not be generated; firmware owns main().');
end

headerText = fileread(fullfile(buildDirectory, 'BmsSupervisor.h'));
requiredSymbols = {'BmsSupervisor_initialize', 'BmsSupervisor_step', ...
    'BmsSupervisor_U', 'BmsSupervisor_Y', 'min_cell_mv', 'max_cell_mv', ...
    'measurement_valid', 'measurement_stale', 'step_ms', ...
    'warning_flags', 'fault_flags', 'charge_allowed_shadow', ...
    'discharge_allowed_shadow'};
for symbolIndex = 1:numel(requiredSymbols)
    if ~contains(headerText, requiredSymbols{symbolIndex})
        error('BmsSupervisor:GeneratedInterfaceMismatch', ...
            'Generated header is missing required symbol %s.', ...
            requiredSymbols{symbolIndex});
    end
end

sourceText = fileread(fullfile(buildDirectory, 'BmsSupervisor.c'));
forbiddenTokens = {'stm32', 'bq76940', 'HAL_', 'bsp_', 'malloc(', 'free('};
combinedText = lower([headerText newline sourceText]);
for tokenIndex = 1:numel(forbiddenTokens)
    if contains(combinedText, lower(forbiddenTokens{tokenIndex}))
        error('BmsSupervisor:ForbiddenGeneratedDependency', ...
            'Generated code contains forbidden token %s.', ...
            forbiddenTokens{tokenIndex});
    end
end

fprintf('  Interface validated for %s.\n', cfg.ModelName);
end

function closeModel(modelName)
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
end
